sudo: true
language: haskell

git:
  depth: 2

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.8.1
  - ghc: 8.6.5
  - ghc: 8.4.4
  - ghc: 8.2.2

install:
  - |
    ghc --version
    cabal --version
    cabal new-update
    cabal new-build all --enable-tests

script:
  - cabal new-test all
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint -XTypeApplications hreq/src/ hreq-core/src/ hreq-conduit/src/

notifications:
  email: false
